server:
  port: 10070
eureka:
  client:
    service-url:
      defaultZone: http://registry1:9001/eureka/, http://registry2:9002/eureka/, http://registry3:9003/eureka/
  instance:
    prefer-ip-address: true